version: '3'
services:
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  api:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  ui:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./ui
    volumes:
      - /app/node_modules
      - ./ui:/app
