name: UI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  PROJECT_DIR: ui

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.PROJECT_DIR}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '${{env.PROJECT_DIR}}/package-lock.json'

      - name: Cache Node Modules
        id: cache-nodemodules
        uses: actions/cache@v4.1.1
        env:
          cache-name: cache-nodemodules
        with:
          path: |
            ui/node_modules
          key: cache-nodemodules-${{ hashFiles('ui/package-lock.json') }}

      - name: Install node modules
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm i

      - name: Lint code for consistent style
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.PROJECT_DIR}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '${{env.PROJECT_DIR}}/package-lock.json'

      - name: Cache Node Modules
        id: cache-nodemodules
        uses: actions/cache@v4.1.1
        env:
          cache-name: cache-nodemodules
        with:
          path: |
            ui/node_modules
          key: cache-nodemodules-${{ hashFiles('ui/package-lock.json') }}

      - name: Install node modules
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm i

      - name: Run tests
        run: CI=true npm run test
